### PR TITLE
Fix crash on initialisation

### PR DESCRIPTION
**Pull request by hebertialmeida**
The current demo project is crashing, I have noticed that because after the last update broke my tests.

screen shot 2016-04-18 at 4 32 39 pm

### CODE REVIEW

**Comment by alexsanderkhitev** [comment]
@hebertialmeida Hello I checked your request. It is excellent

**Comment by alexsanderkhitev** [comment]
I made new release from your pull request. Thank you so much)

**Comment by hebertialmeida** [comment]
@alexsanderkhitev You are welcome!

**Comment by barrault01** [comment]
This break the use of SKLocalPhoto.

**Pull request merged**
