### PR TITLE
Several tweaks and impovements

### PR DESCRIPTION
**Pull request by krummler**
I had some issues regarding the transitions while opening and closing. I also updated the demo app to reflect the changes.

- Changed content mode to `.aspectFill` so images don't become squished
- Add support for cornerRadius transition when opening/closing
- Option to bounce transition when opening/closing
- Offset/size fixed when closing from zoomed/panned state

### CODE REVIEW

**Comment by krummler** [comment]
Updated to have the latest changes from origin

**Comment by alexsanderskywork** [comment]
Hello @krummler ! This may to resolve Keishi

**Comment by krummler** [comment]
Hello @alexsanderskywork :). What do you mean?

I noticed the open/close effect sometimes is broken when the foto is rotated (an image taken from the camera in portrait mode). I think that's already broken on your master, I'll try and work on a fix tomorrow.

**Comment by alexsanderskywork** [comment]
@krummler I mean that Keishi can to merge it. Yes, you are right. There is a bug with rotation of device. I write this code which fix it but there will be another bug when it moves at first to forward then backward or

**Comment by alexsanderskywork** [comment]
```
   if visiblePages.count > 0 {
            let currentIndex = visiblePages.count - 1
            let page = visiblePages[currentIndex]
            page.frame = frameForPageAtIndex(currentPageIndex)
            page.setMaxMinZoomScalesForCurrentBounds()
            if page.captionView != nil {
                page.captionView.frame = frameForCaptionView(page.captionView, index: currentIndex)
            }
        }
```

**Comment by suzuki-0000** [comment]
hi @krummler great works.
@alexsanderskywork makes this repo stable at 1.6.5.
so pull latest master and check the conflicts.

**Comment by krummler** [comment]
Thanks, I merged and updated my master.

I found another problem when using images from the camera roll (it's not showing up for 'normal' photos, so I can't show it in the demo). I'm working on a fix, I'll make a separate pull request when I fixed it.

**Comment by alexsanderskywork** [comment]
Keishi can I merge a pull request from Krummler?

**Pull request merged**
