### PR TITLE
Fixed unit test and problems running when being bridged to objective-c

### PR DESCRIPTION
**Pull request by krummler**
Fixed issues shown here: https://github.com/suzuki-0000/SKPhotoBrowser/pull/100

### CODE REVIEW

**Comment by barrault01** [comment]
tests passed here :-)
👍

**Comment by barrault01** [comment]
@krummler btw #103

**Comment by ddLesha** [comment]
thanks for fixes.

**Comment by barrault01** [comment]
@krummler Merge?

**Comment by krummler** [comment]
Merged and done :)

**Pull request merged**
