### PR TITLE
The pod is currently crashing

### PR DESCRIPTION
**Pull request by barrault01**
Just running the tests will show that the pod is crashing.

### CODE REVIEW

**Comment by barrault01** [comment]
@alexsanderkhitev @suzuki-0000 please review this as soon as possible

**Comment by barrault01** [comment]
@krummler can you?

**Comment by krummler** [comment]
I see it's not working right, but simply changing it to a generic `AnyObject` is a bad plan. Swift promotes more specific types, AnyObject is more like a hack to get it working again. 

The real problem is the array is a protocol now that does not have an Obj-C representation, which it needs to function properly. I'll look into a more robust solution and make a pull request.

**Comment by krummler** [comment]
@barrault01 could you check if this fixes it:

https://github.com/suzuki-0000/SKPhotoBrowser/pull/102

**Comment by barrault01** [comment]
@krummler fully agree with you. It was just a quick fixed to make the pod work again.

**Pull request closed without merging**
